# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

resources:
  pipelines:
    - pipeline: BuildPublishPipeline
      source: jndz2.ado-multiple-pipelines-first

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo $(resource.pipeline.BuildPublishPipeline.pipelineID)
    echo $(resource.pipeline.BuildPublishPipeline.runName)
    echo $(resource.pipeline.BuildPublishPipeline.runID)
    echo $(resource.pipeline.BuildPublishPipeline.runURI)
    echo $(resource.pipeline.BuildPublishPipeline.sourceBranch)
    echo $(resource.pipeline.BuildPublishPipeline.sourceCommit)
    echo $(resource.pipeline.BuildPublishPipeline.sourceProvider)
    echo $(resource.pipeline.BuildPublishPipeline.requestedFor)
    echo $(resource.pipeline.BuildPublishPipeline.requestedForID)


- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'e8a7895f-8c5b-40a2-9948-e39528c7c75b'
    pipeline: '5'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latestFromBranch'
    branchName: 'refs/heads/main'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'